USE [master]
GO

/****** Object:  Database [PELUQUERIA_MILENIUM]    Script Date: 26/09/2022 11:54:59 a. m. ******/
CREATE DATABASE [PELUQUERIA_MILENIUM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PELUQUERIA_MILENIUM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PELUQUERIA_MILENIUM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PELUQUERIA_MILENIUM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PELUQUERIA_MILENIUM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PELUQUERIA_MILENIUM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ARITHABORT OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET RECOVERY FULL 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET  MULTI_USER 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PELUQUERIA_MILENIUM] SET  READ_WRITE 
GO

